# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('gamelibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='game',
            name='editor',
            field=models.ManyToManyField(blank=True, related_name='edited_games', to='gamelibrary.GameEditor', verbose_name='Editor'),
        ),
    ]
