# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibrary', '0002_auto_20170803_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='editor',
        ),
        migrations.AddField(
            model_name='game',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_games', to='gamelibrary.GameEditor', verbose_name='Editor'),
        ),
    ]
