# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibrary', '0003_auto_20170803_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating_sum',
        ),
    ]
