# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gamelibrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('gamelibrary', '0005_auto_20170804_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, gamelibrary.models.AbsoluteURLFromSlugMixin),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='related_games', to='gamelibrary.GameGenre', verbose_name='Genre'),
        ),
    ]
