# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelibrary', '0006_auto_20170804_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('info', models.CharField(max_length=256)),
            ],
        ),
    ]
